// <auto-generated />
using DataAPIDocker.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAPIDocker.Migrations
{
    [DbContext(typeof(CaptainContext))]
    [Migration("20190328200505_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataAPIDocker.Captain", b =>
                {
                    b.Property<int>("CaptainId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("CaptainId");

                    b.ToTable("Captains");

                    b.HasData(
                        new
                        {
                            CaptainId = 1,
                            Name = "Julie Lerman"
                        },
                        new
                        {
                            CaptainId = 2,
                            Name = "Rachid Zarouali"
                        },
                        new
                        {
                            CaptainId = 3,
                            Name = "Michele Bustamante"
                        },
                        new
                        {
                            CaptainId = 4,
                            Name = "Dan Wahlin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
